CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    ts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY,
  status VARCHAR NOT NULL,
  ts INTEGER NOT NULL DEFAULT 0
);
