language: rust
rust:
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_bed59bda57ac_key -iv $encrypted_bed59bda57ac_iv
  -in secure.json.enc -out ~/secure.json -d
deploy:
  provider: gae
  keyfile: "~/secure.json"
  project: rocket-rust-demo
  skip_cleanup: true
